FROM jodogne/orthanc-plugins:1.6.0

MAINTAINER Sebastien Jodogne <s.jodogne@gmail.com>
LABEL Description="Orthanc, free DICOM server" Vendor="The Orthanc project"

RUN apt-get -y clean && apt-get -y update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install python3.7 libpython3.7 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ADD ./docker-build/share/orthanc/plugins/libOrthancPython.so \
    /usr/local/share/orthanc/plugins/libOrthancPython.so
