FROM debian:stable-slim

MAINTAINER Sebastien Jodogne <s.jodogne@gmail.com>
LABEL Description="Orthanc, free DICOM server" Vendor="The Orthanc project"

RUN apt-get -y clean && apt-get -y update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install \
    nano build-essential unzip cmake pkg-config libpython3.7-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
