# 2021-09-15: We don't use "debian:bullseye-slim", as the "mercurial" package
# fails to install on CBlue
FROM debian:buster-slim

MAINTAINER Sebastien Jodogne <s.jodogne@gmail.com>
LABEL Description="Orthanc, free DICOM server" Vendor="The Orthanc project"

RUN apt-get -y clean && apt-get -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
    nano unzip cmake mingw-w64 patch wget bzip2 python mercurial && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
